##1
Name=input("What is your name?"+":"+" ")
print("good, your name is".title()+" "+Name.upper())
print(" ")
print("check the current age of an event".upper())
print(input("what event do you seek?"+" "))
print(" ")
year1=int(input("What year was it?:"+" "))
year2=int(input("what year is it today?:"+" "))
print(f"{year2}-{year1} = {year2-year1} years today")
